### PR TITLE
Use pyramid_redis with socket

### PR DESCRIPTION
**Pull request by rdrongow**
I found this client very handy but missed an option for usage with unix sockets. My ISP only provides a redis via socket. I actually ended up in rewriting some code (mainly in hooks.py), since I did not want to do a quick hack. The main problem was, that I could not just make a difference between URL and socket, since the socket option in the StrictClient results in an object with a different connection pool type. Hope you like it. Let me know, if I messed something up or if it doesn't meet your standards. I think/hope, I did not break anything.

### CODE REVIEW

**Comment by thruflo** [comment]
Hi @rdrongow, 

Thanks for taking the trouble to contribute this. Looks great and certainly would be more flexible to support connection via url or socket.

Couple of notes.  First is that calling `RedisClientConfiguration` updates the instance in place, rather than returning the parsed config as a dict.  Minor point but I'd prefer to return a value.

Second is that the revised implementation breaks some (arbitrary and undocumented) behaviour I'm relying on: that `config.include('pyramid_redis')` without any configuration connects by default to `redis://localhost:6379`. I think a solution would be to retain the redis.url default in [config.py](https://github.com/rdrongow/pyramid_redis/blob/master/src/pyramid_redis/config.py#L16):

``` python
'redis.url': os.environ.get(REDIS_URL,'redis://localhost:6379'),
```

Then in the client configuration class tweak the conditional to fallback on url if socket isn't provided:

``` python
if settings['redis.unix_socket_path'] is not None:
    config['unix_socket_path'] = settings['redis.unix_socket_path']
else: # defaults to `redis://localhost:6379`
    url = self.parse_url(settings['redis.url'])
    config.update({
        'host': url.hostname,
        'port': url.port,
    })
    if url.password:
        config['password'] = url.password
    max_connections = settings.get('redis.max_connections', None)
    if max_connections is not None:
        config['max_connections'] = int(max_connections)
    config = {'connection_pool': self.pool_cls(**config)}
```

If you agree and are happy to update the pull request that would be great.  Or let me know if you don't have time and I'll do it.

Thanks,

James.

**Comment by rdrongow** [comment]
Hi James,
sounds all good to me. I'll change it at some point this week. Thanks for taking the time to consider my changes.

Cheers, Ron

**Comment by rdrongow** [comment]
Hi James,

I've just commited something very close to you suggestions. I figured, that it'd be better to fail a little better, since you never know who might use this stuff in different contexts - even though unlikeley, I know =D

**Comment by thruflo** [comment]
Thanks again for this :)

(sorry didn't merge earlier, just back from holiday today).

**Comment by rdrongow** [comment]
I actually have to thank you for putting this up in the first place. I was happy to find it.

**Comment by rdrongow** [comment]
Hey James,

one more question. Would you mind uploading a new version of this on pypi? Greetings, Ron

**Comment by thruflo** [comment]
Sure, have done: https://pypi.python.org/pypi/pyramid_redis/0.1.4

James.

**Pull request merged**
